### ISSUE TITLE
Can't get it to work - Wrong volume paths in the container? 

### ISSUE THREAD

**Issue by DuvelCorp** [sentriz/betanin#115]
Hi

Betanin and Beets running from the same stack in Portainer

```
version: "2.1"
services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Brussels
    volumes:
      - /media/seedbox/.config/beets:/config
      - /nfs/media/musique:/music
      - /media/seedbox/slskdownloads/complete:/downloads
    ports:
      - 8337:8337
    restart: unless-stopped

  betanin:
    image: sentriz/betanin
    container_name: betanin
    ports:
      - 9393:9393
    restart: unless-stopped
    environment:
      - UID=1001
      - GID=1001
      - TZ=Europe/Brussels
    volumes:
      - /media/seedbox/.config/betanin/data/:/b/.local/share/betanin/
      - /media/seedbox/.config/betanin/config/:/b/.config/betanin/
      - /media/seedbox/.config/beets/:/b/.config/beets/
      - /nfs/media/musique:/music
      - /media/seedbox/slskdownloads/complete:/downloads    
```

Beets work perfectly. ie when I run the import task with
`docker exec -u abc -it beets /bin/bash -c 'beet import /downloads'`
It starts the import, parse the downloads, ask me questions, move files.

But import task is failing in Betanin
There's not a hint of issue that could lead me on the right track.
When I start everything from scratch, betanin starts without error, creates config file in /config folder, and betanin.db and secret_key in /data folder.

Everything looks OK in the web GUI, and in the settings/beet config, I can see my beets config.yaml which prove that folders are correctly set.
The 2 containers are properly running with the same user "seedbox" and following all my debugging, I even granted a chmod 777 on both folders.
![image](https://github.com/sentriz/betanin/assets/33682764/d6887cc1-6f06-4c3a-b7af-bf1454ee071d)

When I go in betanin torrent GUI, I can browse everything 
![image](https://github.com/sentriz/betanin/assets/33682764/d1bba454-95f7-454c-95a8-3e6c47942241)

But looks at what happens when I run the import task

![image](https://github.com/sentriz/betanin/assets/33682764/b7c7fe6e-70b8-4482-97fe-b5932fe8336e)
```
[betanin] starting cli program

/usr/lib/python3.11/site-packages/beetsplug/extrafiles.py:12: UserWarning: beets.mediafile is deprecated; use mediafile instead
  import beets.mediafile

The database directory /config does not                        exist. Create it (Y/n)? 
```
First, this makes no sense at all. All directories exists. And I can browse the config directories I defined in the container volume, using the torrent GUI.

If I answer N, I have this

![image](https://github.com/sentriz/betanin/assets/33682764/fc0a1863-077a-4528-8d26-6540213cebbe)

Since it is seems to be looking for the  file /config/musiclibrary.blb, I assume it can't find the config folder of beets.
But it is there, and the DB is there too. And it has access to it because its the same owner
![image](https://github.com/sentriz/betanin/assets/33682764/a81c59e5-189f-4731-bfc0-5e20231026c0)

Also the complete nonsense is, as explained before, that I can see the beets config file in the betanin settings. So it is obvsious that it can access it and that my container volumes config is correct.

If I answer Y, I have this
![image](https://github.com/sentriz/betanin/assets/33682764/2fdeba32-5a17-41d9-83b0-c02cf18de4e2)

And it makes no sense. it can't have a permission denied if its is working on the folders defined in the docker-compose volumes. The user running the 2 containers are the same a,d I triple checked all permissions and ownership are correct on the real linux folders.

So all this make me think that the issue is not on my side.

Cheers.
